# Generated by Django 4.1.7 on 2023-12-23 10:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0054_questionset_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0033_alter_usertests_date_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertests',
            name='date_before',
            field=models.DateTimeField(default=datetime.date(2024, 1, 22), verbose_name='Дата до которой необходимо выполнить тест'),
        ),
        migrations.CreateModel(
            name='QuestionEditorBookMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize737.questionset', verbose_name='Модель вопроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Модель пользователя')),
            ],
        ),
    ]
