# Generated by Django 4.1.6 on 2023-02-15 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quize_name', models.CharField(help_text='Вид Теста + кол-во вопросов', max_length=200, verbose_name='Название теста')),
                ('user_under_test', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions_ids', models.CharField(max_length=200, null=True, verbose_name='Номера вопросов')),
            ],
        ),
        migrations.CreateModel(
            name='Thems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название Темы')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('option_1', models.CharField(max_length=500, verbose_name='Вариант 1')),
                ('option_2', models.CharField(max_length=500, verbose_name='Вариант 2')),
                ('option_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вариант 3')),
                ('option_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Вариант 4')),
                ('answer', models.IntegerField(verbose_name='Ответ, в виде номера строки ответа')),
                ('them_name', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='quize737.thems', verbose_name='Тема Вопроса')),
            ],
            options={
                'ordering': ['-them_name'],
            },
        ),
    ]
