# Generated by Django 4.1.6 on 2023-02-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizeset',
            name='q_sequence_num',
            field=models.IntegerField(default=0, verbose_name='Номер последовательного вопроса в тесте в процессе прохождения теста'),
        ),
    ]
