# Generated by Django 4.1.6 on 2023-02-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0002_quizeset_q_sequence_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='q_kind',
            field=models.BooleanField(default=False, help_text='Подразумевает ли вопрос множественные ответы', verbose_name='Вид вопроса'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='q_weight',
            field=models.IntegerField(default=0, help_text='Если вопрос сложный или лёгкий, кол-во баллов за вопрос можно увеличить или уменьшить', verbose_name='"Вес вопроса"'),
        ),
    ]
