# Generated by Django 4.1.6 on 2023-02-16 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0003_questionset_q_kind_questionset_q_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizeResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Имя пользователя, который проходил тест', max_length=255, verbose_name='Имя пользователя')),
                ('quize_name', models.CharField(help_text='Имя Теста + кол-во вопросов (без пробелов)', max_length=200, verbose_name='Название теста')),
                ('total_num_q', models.IntegerField(help_text='Общее количество вопросов в тесте', verbose_name='Количество вопросов')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('correct_q_num', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('score_number', models.IntegerField(verbose_name='Количество баллов')),
            ],
        ),
        migrations.AlterField(
            model_name='quizeset',
            name='quize_name',
            field=models.CharField(help_text='Имя Теста + кол-во вопросов (без пробелов)', max_length=200, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='quizeset',
            name='user_under_test',
            field=models.CharField(help_text='Имя пользователя, который проходит тест', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
