# Generated by Django 4.1.6 on 2023-02-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0006_quizeset_max_score_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizeresults',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='quizeset',
            name='timestamp',
        ),
    ]
