# Generated by Django 4.1.7 on 2023-12-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize737', '0053_alter_quizeresults_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если вопрос не активен, то в тест пользователю он не попадает', verbose_name='Не активный вопрос'),
        ),
    ]
