# Generated by Django 4.1.7 on 2023-12-23 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время и дата события')),
                ('description', models.TextField(verbose_name='Описание изменения')),
                ('test_name', models.CharField(blank=True, help_text='Название теста, если он учавствует в событии', max_length=500, null=True, verbose_name='Название теста')),
                ('test_date_due', models.DateTimeField(help_text='Дата до которой надо выполнить тест', null=True, verbose_name='Время и дата события')),
                ('user_done', models.TextField(help_text='ФИО пользователя который сделал изменения', verbose_name='Описание изменения')),
                ('user_changed', models.ForeignKey(help_text='Объект пользователя который подвергся изменениям', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
